import fs from 'fs';
import path from 'path';
import chalk from 'chalk';
import { ScanIssue } from '../spec/schema.js';

const CATEGORY_SECTION_COMMENTS: Record<string, string> = {
  runtime:    '# ── Runtime Version Fixes ──────────────────────────────────',
  dependency: '# ── Dependency Fixes ───────────────────────────────────────',
  env:        '# ── Environment Variable Fixes ─────────────────────────────',
  path:       '# ── Path / Import Fixes ────────────────────────────────────',
  tooling:    '# ── Tooling Setup ──────────────────────────────────────────',
  docker:     '# ── Docker Setup ───────────────────────────────────────────',
};

function issueToCommands(issue: ScanIssue): string[] {
  const lines: string[] = [];

  if (issue.fixHint) {
    lines.push(`# ${issue.title}`);
    // Split multi-line hints into separate commands
    issue.fixHint.split('\n').forEach(l => lines.push(l.trim()));
  } else {
    lines.push(`# ${issue.title}`);
    lines.push(`# TODO: ${issue.detail}`);
  }

  return lines;
}

export function generateSetupScript(issues: ScanIssue[], outputPath: string): void {
  const now = new Date().toISOString();
  const lines: string[] = [
    '#!/usr/bin/env bash',
    '# ================================================================',
    '# dx-setup.sh — Generated by DX-Ray Trace',
    `# Generated: ${now}`,
    '# Run this script to resolve issues that dx fix cannot auto-fix.',
    '# Review each command before running!',
    '# ================================================================',
    '',
    'set -e',
    '',
  ];

  // Group by category
  const byCategory = new Map<string, ScanIssue[]>();
  for (const issue of issues) {
    const list = byCategory.get(issue.category) ?? [];
    list.push(issue);
    byCategory.set(issue.category, list);
  }

  for (const [cat, catIssues] of byCategory.entries()) {
    lines.push(CATEGORY_SECTION_COMMENTS[cat] ?? `# ── ${cat} ──`);
    lines.push('');
    for (const issue of catIssues) {
      issueToCommands(issue).forEach(l => lines.push(l));
      lines.push('');
    }
  }

  lines.push('echo "✅ Setup complete! Run dx scan to verify your environment."');

  fs.writeFileSync(outputPath, lines.join('\n'), 'utf-8');
  try {
    // Make executable on Unix
    fs.chmodSync(outputPath, 0o755);
  } catch {
    // Ignore on Windows
  }
}
