import { execSync } from 'child_process';
import path from 'path';
import fs from 'fs';
import os from 'os';
import yaml from 'js-yaml';
import chalk from 'chalk';
import stripBom from 'strip-bom';
import { DxSpec } from '../spec/schema.js';

function runSafe(cmd: string): string | null {
  try {
    return execSync(cmd, { encoding: 'utf-8', timeout: 5000, stdio: ['pipe', 'pipe', 'pipe'] }).trim();
  } catch {
    return null;
  }
}

function detectNodeVersion(): string | null {
  const v = runSafe('node --version');
  return v ? v.replace(/^v/, '') : null;
}

function detectPythonVersion(): string | null {
  return runSafe('python --version 2>&1')?.match(/(\d+\.\d+\.\d+)/)?.[1]
    ?? runSafe('python3 --version 2>&1')?.match(/(\d+\.\d+\.\d+)/)?.[1]
    ?? null;
}

function detectNpmDeps(projectDir: string): string[] {
  const pkgPath = path.join(projectDir, 'package.json');
  if (!fs.existsSync(pkgPath)) return [];
  const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8'));
  return Object.keys({ ...(pkg.dependencies ?? {}), ...(pkg.devDependencies ?? {}) });
}

function detectEnvKeys(projectDir: string): Array<{ key: string; required: boolean; example?: string }> {
  const envExamplePath = path.join(projectDir, '.env.example');
  if (!fs.existsSync(envExamplePath)) return [];

  const raw = fs.readFileSync(envExamplePath, 'utf-8');
  const content = stripBom(raw).replace(/[\uFFFD\uFEFF\u0000]/g, '');
  const vars: Array<{ key: string; required: boolean; example?: string }> = [];
  for (const line of content.split('\n')) {
    let trimmed = line.trim();
    // remove any residual carriage returns or null bytes
    trimmed = trimmed.replace(/[\r\0]/g, '');
    if (!trimmed || trimmed.startsWith('#')) continue;
    
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx <= 0) continue;
    
    const key = trimmed.slice(0, eqIdx).trim().replace(/[^a-zA-Z0-9_]/g, '');
    const val = trimmed.slice(eqIdx + 1).trim().replace(/[\r\0]/g, '');
    
    if (key) {
      vars.push({ key, required: true, example: val || undefined });
    }
  }
  return vars;
}

function detectDockerCompose(projectDir: string): string | undefined {
  const candidates = ['docker-compose.yml', 'docker-compose.yaml', 'compose.yml', 'compose.yaml'];
  for (const c of candidates) {
    if (fs.existsSync(path.join(projectDir, c))) return c;
  }
  return undefined;
}

function detectRequiredFiles(projectDir: string): string[] {
  const candidates = ['README.md', '.env.example', 'package.json', 'requirements.txt', 'Makefile', 'Dockerfile'];
  return candidates.filter(f => fs.existsSync(path.join(projectDir, f)));
}

export function generateSpec(projectDir: string, projectName?: string): DxSpec {
  const node = detectNodeVersion();
  const python = detectPythonVersion();

  const spec: DxSpec = {
    name: projectName ?? path.basename(projectDir),
    version: '1.0.0',
  };

  // Runtime
  const runtime: DxSpec['runtime'] = {};
  if (node) runtime.node = node.split('.')[0] + '.x'; // e.g. "20.x"
  if (python) runtime.python = python.split('.').slice(0, 2).join('.') + '.x'; // e.g. "3.11.x"
  if (Object.keys(runtime).length > 0) spec.runtime = runtime;

  // Env vars
  const envVars = detectEnvKeys(projectDir);
  if (envVars.length > 0) spec.env = envVars;

  // Dependencies
  const npmDeps = detectNpmDeps(projectDir);
  if (npmDeps.length > 0) spec.dependencies = { npm: npmDeps };

  // Paths
  const requiredFiles = detectRequiredFiles(projectDir);
  spec.paths = {
    noHardcodedPaths: true,
    requiredFiles: requiredFiles.length > 0 ? requiredFiles : undefined,
  };

  // Tooling
  const hasDocker = runSafe('docker --version') !== null;
  const hasGit = runSafe('git --version') !== null;
  const hasNvm = runSafe('nvm --version') !== null;
  if (hasDocker || hasGit || hasNvm) {
    spec.tooling = { docker: hasDocker, git: hasGit, nvm: hasNvm };
  }

  // Docker compose file
  const composeFile = detectDockerCompose(projectDir);
  if (composeFile) {
    spec.docker = { composeFile };
  }

  return spec;
}

export function writeSpec(spec: DxSpec, outputPath: string): void {
  const header = [
    '# dx-spec.yaml — DX-Ray Trace Project Specification',
    '# Generated by: dx init',
    `# Date: ${new Date().toISOString()}`,
    '# Edit this file to define your project requirements.',
    '',
  ].join('\n');

  const content = header + yaml.dump(spec, { indent: 2, noRefs: true });
  fs.writeFileSync(outputPath, content, 'utf-8');
}
